sg_logstash:
  users:
    - logstash

sg_kibana_server:
  users:
    - kibanaserver

sg_all_access:
  users:
    - qbunt
    - bbiagas
    - dragon
    - channaford
    - gbodi
    - jcrown
    - pcalvillo
    - htaylor
