version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch-data:/usr/share/elasticsearch/data
      - /home/ubuntu/certs/esnode.pem:/usr/share/elasticsearch/config/esnode.pem
      - /home/ubuntu/certs/esnode-key.pem:/usr/share/elasticsearch/config/esnode-key.pem
      - /home/ubuntu/certs/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - /home/ubuntu/certs/kirk.pem:/usr/share/elasticsearch/config/kirk.pem
      - /home/ubuntu/certs/kirk-key.pem:/usr/share/elasticsearch/config/kirk-key.pem
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - elk

  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "5000:5000"
      - "5001:5001/udp"
      - "5002:5002/udp"
      - "5003:5003"
    environment:
      LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
