---
- hosts: all
  vars_files:
    - ./vars/users.yml
  tasks:
    - name: Create searchguard users
      template:
        src: ./templates/users.j2
        dest: ../elasticsearch/config/sg_internal_users.yml
